### ISSUE TITLE
Decide what to do now that upstream has an official package on Packagist

### ISSUE THREAD

**Issue by marclaporte** [etd-framework/pivottable#1]
https://github.com/etd-framework/pivottable reports being a "Shim repository for PivotTable.js"

Just recently, PivotTable.js started being offered by upstream:
https://github.com/nicolaskruchten/pivottable/blob/master/composer.json
https://packagist.org/packages/nicolaskruchten/pivottable

And it's set up in such a way that it's automatically updated when a new version is released.

So do you want to keep this one anyway?

Thanks!

Marc Laporte
-- 
http://WikiSuite.org
http://PluginProblems.com
http://Avan.Tech

**Comment by jbanety** [comment]
Great to to hear that!
I'll make this repo deprecated.
Thanks.
